name: 🔮UI Одноклассники
on:
  push:
    branches: homework
  pull_request:
    branches: homework
  #workflow_dispatch: верну, когда залью в ветку main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LANG: ru_RU.UTF-8
      LANGUAGE: ru_RU.UTF-8
      LC_ALL: ru_RU.UTF-8
    steps:
      - name: Set up locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen ru_RU.UTF-8
          echo "LANG=ru_RU.UTF-8" | sudo tee /etc/default/locale
          echo "LC_ALL=ru_RU.UTF-8" | sudo tee -a /etc/default/locale
          source /etc/default/locale
          echo "Локаль установлена: $(locale)"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run UI tests with Maven
        run: mvn test -Dtest=CheckTapeTest -Dallure.results.directory=target/allure-results
        env:
          BROWSER: chrome
          LOGIN: ${{ secrets.USER_LOGIN }}
          PASSWORD: ${{ secrets.USER_PASSWORD }}

      - name: Copy History
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages
      - name: Build Report
        uses: simple-elf/allure-report-action@v1.10
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20
      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history



